[package]
name = "process_meminfo_win"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"

[dependencies.windows]
version = "0.30.0"
features = [
    "Win32_Foundation",
    "Win32_System_ProcessStatus"
]
